footer: "Error message"

embeds:
- id: "blacklisted_for_command"
  title: "Blacklisted"
  description: "You are unable to run this command since you have been blackilisted."
  timestamp: true
  color: "#ff0000"

- id: "unallowed_for_command"
  title: "Not enough permissions"
  description: "You are unable to run this command as you lack permissions to do so.\nIf you think you should be able to run this command, please get in touch with the server owners."
  timestamp: true
  color: "#ff0000"

- id: "no_panel_title"
  title: "Unexistent panel title"
  description: "The panel title has not been set in `./configs/language` at `tickets.panel_title`."
  timestamp: true
  color: "#ff0000"

- id: "no_panel_description"
  title: "Unexistent panel description"
  description: "The panel message has not been set in `./configs/language` at `tickets.panel_message`."
  timestamp: true
  color: "#ff0000"

- id: "no_categories"
  title: "Missing categories"
  description: "The categories for tickets have not been seet in `./configs/tickets.yml` at `categories`."
  timestamp: true
  color: "#ff0000"

- id: "no_ticket_channel"
  title: "The channel is not a ticket"
  description: "The channel selected does not appear to be a ticket, to run this command outside of a ticket you should specify the channel"
  timestamp: true
  color: "#ff0000"

- id: "member_unremovable"
  title: "The user cannot be removed"
  description: "Unable to remove this user since it has a role wich gives acces to all tickets"
  timestamp: true
  color: "#ff0000"

- id: "ticket_already_assigned"
  title: "The ticket has already been assigned"
  description: "The ticket you are trying to cliam has already been assigned"
  timestamp: true
  color: "#ff0000"

- id: "ticket_not_assigned"
  title: "The ticket has not been assigned"
  description: "The ticket you are trying to unassign has not been assigned"
  timestamp: true
  color: "#ff0000"

- id: "closed_ticket"
  title: "The ticket is closed"
  description: "To perform this action the ticket must be open, you can open it with `/tck-reopen <ticket_channel>`"
  timestamp: true
  color: "#ff0000"

- id: "unclosed_ticket"
  title: "The ticket is already opened"
  description: "To reopen a ticket, it must have been closed before. Are you sure you selected the right ticket?"
  timestamp: true
  color: "#ff0000"