footer: "Success message"

embeds:
- id: "ticket_opened"
  title: "Ticket opened"
  #variables available: <ticket-channel>
  description: "The ticket channel <ticket-channel> has been successfully opened.\nYou can click the button down below to be redirected to the ticket channel.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_user_added"
  title: "User added"
  #variables available: <user-added>, <ticket-channel>
  description: "The user <user-added> was successfully added to the ticket <ticket-channel>.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_user_removed"
  title: "User removed"
  #variables available: <user-removed>, <ticket-channel>
  description: "The user <user-removed> was successfully removed from the ticket <ticket-channel>.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_assigned"
  title: "Ticket assigned"
  #variables available: <user-assignee>, <ticket-channel>
  description: "The ticket <ticket-channel> has been successfully assigned to <user-assignee>.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_unassigned"
  title: "Ticket unassigned"
  #variables available: <ticket-channel>
  description: "The ticket <ticket-channel> is now assigned to no one.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_closed"
  title: "Ticket closed"
  #variables available: <ticket-channel>
  description: "The ticket <ticket-channel> has been successfully closed.\nYee ha!"
  timestamp: true
  color: "#00ff00"

- id: "ticket_deleted"
  title: "Ticket deleted"
  #variables available: <ticket-channel>
  description: "The ticket <ticket-channel> has been successfully deleted.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  
- id: "ticket_reopened"
  title: "Ticket opened"
  #variables available: <ticket-channel>
  description: "The ticket <ticket-channel> has been successfully reopened.\nYee ha!"
  timestamp: true
  color: "#00ff00"
  